fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      image
    }
    ... on PageBlocksProjects {
      heading
      subheading
      items {
        __typename
        image
        name
        decscription
        href
      }
    }
    ... on PageBlocksFeatures {
      heading
      subheading
      items {
        __typename
        title
        link
        href
      }
    }
    ... on PageBlocksFinancial {
      heading
      items {
        __typename
        content
      }
    }
    ... on PageBlocksContact {
      heading
    }
    ... on PageBlocksInformation {
      image
      subheading
      items {
        __typename
        image
        name
        decscription
        href
      }
      mapimage
    }
    ... on PageBlocksFooter {
      content
    }
  }
}

fragment PostParts on Post {
  title
  image
  description
}
